spine1:
  hostname: spine1
  groups:
    - spines
  data:
    ipv4: 192.168.122.11/24
    router_id: 10.0.0.11
    gns3_port: '5001'
spine2:
  hostname: spine2
  groups:
    - spines
  data:
    ipv4: 192.168.122.12/24
    router_id: 10.0.0.12
    gns3_port: '5005'
leaf1:
  hostname: leaf1
  groups:
    - leaves
  data:
    ipv4: 192.168.122.21/24
    router_id: 10.0.0.21
    gns3_port: '5003'
leaf2:
  hostname: leaf2
  groups:
    - leaves
  data:
    ipv4: 192.168.122.22/24
    router_id: 10.0.0.22
    gns3_port: '5009'